use crate::extern_function::navite_exception_module::{
    HError, OPEN_STG_ERROR_CODE_CORE_CORE_STL_ALLOC_ERROR,
    OPEN_STG_ERROR_CODE_CORE_INVALID_PARAMETER, OPEN_STG_ERROR_CODE_CORE_MEMORY_ERROR,
    OPEN_STG_ERROR_CODE_CORE_MODULE_EXIST, OPEN_STG_ERROR_CODE_CORE_MODULE_NOT_EXIST,
    OPEN_STG_ERROR_CODE_CORE_NO_ERROR, OPEN_STG_ERROR_CODE_CORE_NOT_INITIALIZED,
    OPEN_STG_ERROR_CODE_CORE_OUT_OF_RANGE, OPEN_STG_ERROR_CODE_CORE_UNDEFINED_MEMORY_ERROR,
    OPEN_STG_NAMESPACE_CORE, make_error,
};

pub const CORE_EXCEPTION_NO_ERROR: HError =
    make_error(OPEN_STG_NAMESPACE_CORE, OPEN_STG_ERROR_CODE_CORE_NO_ERROR);
pub const CORE_EXCEPTION_CPP_CORE_STANDARD_TEMPLATE_LIBRARY_ALLOC_ERROR: HError = make_error(
    OPEN_STG_NAMESPACE_CORE,
    OPEN_STG_ERROR_CODE_CORE_CORE_STL_ALLOC_ERROR,
);
pub const CORE_EXCEPTION_MEMORY_ERROR: HError = make_error(
    OPEN_STG_NAMESPACE_CORE,
    OPEN_STG_ERROR_CODE_CORE_MEMORY_ERROR,
);

pub const CORE_EXCEPTION_UNDEFINED_MEMORY_ERROR: HError = make_error(
    OPEN_STG_NAMESPACE_CORE,
    OPEN_STG_ERROR_CODE_CORE_UNDEFINED_MEMORY_ERROR,
);

pub const CORE_EXCEPTION_INVALID_PARAMENT: HError = make_error(
    OPEN_STG_NAMESPACE_CORE,
    OPEN_STG_ERROR_CODE_CORE_INVALID_PARAMETER,
);

pub const CORE_EXCEPTION_MODULE_EXIST: HError = make_error(
    OPEN_STG_NAMESPACE_CORE,
    OPEN_STG_ERROR_CODE_CORE_MODULE_EXIST,
);

pub const CORE_EXCEPTION_MODULE_NOT_EXIST: HError = make_error(
    OPEN_STG_NAMESPACE_CORE,
    OPEN_STG_ERROR_CODE_CORE_MODULE_NOT_EXIST,
);
pub const CORE_EXCEPTION_NOT_INITIALIZED: HError = make_error(
    OPEN_STG_NAMESPACE_CORE,
    OPEN_STG_ERROR_CODE_CORE_NOT_INITIALIZED,
);
pub const CORE_EXCEPTION_OUT_OF_RANGE: HError = make_error(
    OPEN_STG_NAMESPACE_CORE,
    OPEN_STG_ERROR_CODE_CORE_OUT_OF_RANGE,
);
