if(POLICY CMP0167)
    cmake_policy(SET CMP0167 NEW)
endif()

include(FetchContent)

# find_package(Boost REQUIRED CONFIG COMPONENTS json program_options)
find_package(Lua REQUIRED 5)
find_package(PkgConfig)
find_package(ICU REQUIRED COMPONENTS i18n data io)
find_package(popt QUIET)
find_package(LibXml2 REQUIRED)
find_package(cJSON CONFIG)
find_package(bson REQUIRED)
find_package(pcre2 QUIET)
find_package(LLVM CONFIG)
find_package(Clang CONFIG)

if(PkgConfig_FOUND)
    pkg_check_modules(XDG_DESKTOP_PORTAL IMPORTED_TARGET xdg-desktop-portal)
    pkg_check_modules(GTK4 IMPORTED_TARGET gtk4)
    pkg_check_modules(MCFGHREAD IMPORTED_TARGET mcfgthread)
    pkg_check_modules(LIBDWARF IMPORTED_TARGET libdwarf)
    pkg_check_modules(LIBPOPT IMPORTED_TARGET REQUIRED popt)
    pkg_check_modules(LIBCJSON IMPORTED_TARGET libcjson)
    pkg_check_modules(LIBXML2 IMPORTED_TARGET libxml-2.0)
    pkg_check_modules(LIBPCRE2 IMPORTED_TARGET libpcre2-8)
endif()

if(TARGET PCRE2::8BIT)
    set(OPEN_STG_TARGET_HAS_PCRE2 TRUE)
    set(OPEN_STG_TARGET_PCRE2 PCRE2::8BIT)
elseif(TARGET PkgConfig::LIBPCRE2)
    set(OPEN_STG_TARGET_HAS_PCRE2 TRUE)
    set(OPEN_STG_TARGET_PCRE2 PkgConfig::LIBPCRE2)
else()
    message(FATAL_ERROR "libpcre2 not found.")
endif()

if(${OPEN_STG_ENABLE_UNIT_TESTS})
    find_package(Catch2 QUIET REQUIRED)
endif()
if(${OPEN_STG_ENABLE_GAME_CLIENT})
    find_package(SDL3 CONFIG REQUIRED)
    find_package(SDL3_ttf CONFIG REQUIRED)
    find_package(SDL3_image CONFIG REQUIRED)
    find_package(SDL3_mixer CONFIG REQUIRED)
endif()
if(${OPEN_STG_ENABLE_LIBDWARF})
    find_package(libdwarf CONFIG)
    if(${PkgConfig_FOUND})
        pkg_check_modules(LIBDWARF IMPORTED_TARGET libdwarf)
    endif()
endif()
if(${OPEN_STG_ENABLE_LIBDWARF})
    if((TARGET PkgConfig::LIBDWARF))
        set(OPEN_STG_TARGET_HAS_LIBDWARF TRUE)
        set(OPEN_STG_TARGET_LIBDWARF PkgConfig::LIBDWARF)
    elseif((TARGET libdwarf::dwarf))
        set(OPEN_STG_TARGET_HAS_LIBDWARF TRUE)
        set(OPEN_STG_TARGET_LIBDWARF libdwarf::dwarf)
    else()
        message(FATAL_ERROR "libdwarf not found.")
    endif()
else()
    set(OPEN_STG_TARGET_HAS_LIBDWARF FALSE)
endif()

if(${OPEN_STG_ENABLE_DEVELOP_TOOLS} AND ("${OPEN_STG_DEVELOP_TOOLS_TYPE}" STREQUAL "CLANG"))
    if("${LLVM_FOUND}" AND "${CLANG_FOUND}")
        set(OPEN_STG_ENABLE_DEVELOP_TOOLS TRUE)
    else()
        message(WARNING "Llvm or clang is not found.")
        set(OPEN_STG_ENABLE_DEVELOP_TOOLS FALSE)
    endif()
else()
    set(OPEN_STG_ENABLE_DEVELOP_TOOLS FALSE)
endif()

if((TARGET PkgConfig::LIBPOPT))
    set(OPEN_STG_TARGET_HAS_POPT TRUE)
    set(OPEN_STG_TARGET_POPT PkgConfig::LIBPOPT)
endif()

if(TARGET cJSON::cJSON)
    set(OPEN_STG_TARGET_HAS_CJSON TRUE)
    set(OPEN_STG_TARGET_CJSON cJSON::cJSON)
elseif(TARGET PkgConfig::LIBCJSON)
    set(OPEN_STG_TARGET_HAS_CJSON TRUE)
    set(OPEN_STG_TARGET_CJSON PkgConfig::LIBCJSON)
else()
    message(FATAL_ERROR "Require libcjson.")
endif()

if(TARGET LibXml2::LibXml2)
    set(OPEN_STG_TARGET_HAS_LIBXML2 TRUE)
    set(OPEN_STG_TARGET_LIBXML2 LibXml2::LibXml2)
elseif(TARGET PkgConfig::LIBXML2)
    set(OPEN_STG_TARGET_HAS_LIBXML2 TRUE)
    set(OPEN_STG_TARGET_LIBXML2 PkgConfig::LIBXML2)
else()
    message(FATAL_ERROR "Require libcjson.")
endif()

set(McfGThreads_DOWNLOAD_FROM_NETWORK TRUE)
set(McfGThreads_DOWNLOAD_SOURCE ustc)
if(${OPEN_STG_ENABLE_MCFGTHREAD})
    find_package(McfGThreads QUIET REQUIRED)
else()
    set(THREADS_PREFER_PTHREAD_FLAG ON)
    find_package(Threads QUIET)
    find_package(PThreads4W QUIET CONFIG)
    if(TARGET Threads::Threads)
        set(OPEN_STG_TARGET_HAS_THREADS TRUE)
        set(OPEN_STG_TARGET_THREADS Threads::Threads)
    elseif(TARGET PThreads4W::PThreads4W)
        set(OPEN_STG_TARGET_HAS_THREADS TRUE)
        set(OPEN_STG_TARGET_THREADS PThreads4W::PThreads4W)
    else()
        set(OPEN_STG_TARGET_HAS_THREADS FALSE)
        # message(FATAL_ERROR "Require pthread4w or mcfgthread.")
    endif()
endif()

# if(${OPEN_STG_OPTION_STRING_PROCESSING_AUTO})
#     if(${PkgConfig_FOUND})
#         pkg_check_modules(LIBBSD IMPORTED_TARGET libbsd)
#         pkg_check_modules(LIBSAFEC IMPORTED_TARGET libsafec)
#     endif()
#     if(${LIBBSD_FOUND})
#         set(OPEN_STG_STRING_PROCESSING_LIBRARY "libbsd")
#         set(OPEN_STG_TARGET_STRING_PROCESSING_LIBRARY PkgConfig::LIBBSD)
#     elseif(${WIN32})
#         set(OPEN_STG_STRING_PROCESSING_LIBRARY "stdc")
#         set(OPEN_STG_TARGET_STRING_PROCESSING_LIBRARY "")
#     else()
#         set(OPEN_STG_STRING_PROCESSING_LIBRARY "libsafec")
#         set(OPEN_STG_TARGET_STRING_PROCESSING_LIBRARY PkgConfig::LIBSAFEC)
#     endif()
# else()
#     if("${OPEN_STG_STRING_PROCESSING_LIBRARY}" MATCHES [=[^([Ll]ib[Bb][Ss][Dd]|LIBBSD)$]=])
#         pkg_check_modules(LIBBSD IMPORTED_TARGET REQUIRED libbsd)
#         set(OPEN_STG_TARGET_STRING_PROCESSING_LIBRARY PkgConfig::LIBBSD)
#     elseif("${OPEN_STG_STRING_PROCESSING_LIBRARY}" MATCHES [=[^([Ll]ib[Ss]afe[Cc]|[Ss]afe[Cc]lib)$]=])
#         pkg_check_modules(LIBSAFEC IMPORTED_TARGET REQUIRED libsafec)
#         set(OPEN_STG_TARGET_STRING_PROCESSING_LIBRARY PkgConfig::LIBSAFEC)
#     elseif()
#         set(OPEN_STG_STRING_PROCESSING_LIBRARY "")
#     endif()
# endif()
