[package]
name = "open_stg_logic_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
open_stg_base_lib_wapper ={ path = "../open_stg_base_lib"}
thunk-rs = "0.3.5"
vc-ltl = "5.3.1"

[build-dependencies]
build_scripts = { path = "../build_scripts" }

[lib]
crate-type = ["cdylib"]

[features]
thunk-rs = ["lib"]