[package]
name = "open_stg_logic_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.11.0"
open_stg_base_lib_wapper ={ path = "../open_stg_base_lib_wapper"}

[build-dependencies]
build_scripts = { path = "../build_scripts" }

[lib]
crate-type = ["cdylib"]

[target.'cfg(all(target_os = "windows",target_env = "msvc"))'.dependencies]
vc-ltl = "*"

