if(POLICY CMP0167)
    cmake_policy(SET CMP0167 NEW)
endif()

include(FetchContent)

# find_package(Boost REQUIRED CONFIG COMPONENTS json program_options)
find_package(SDL3 CONFIG REQUIRED)
find_package(SDL3_ttf CONFIG REQUIRED)
find_package(SDL3_image CONFIG REQUIRED)
find_package(SDL3_mixer CONFIG REQUIRED)
find_package(Lua REQUIRED 5)
find_package(PkgConfig QUIET)
find_package(ICU REQUIRED COMPONENTS i18n data io)
find_package(PThreads4W QUIET CONFIG)
find_package(Catch2 QUIET REQUIRED)
# find_package(popt QUIET)
find_package(libxml2 REQUIRED)
find_package(cJSON CONFIG REQUIRED)
find_package(bson QUIET REQUIRED)
find_package(libdwarf CONFIG)
find_package(LLVM CONFIG)
find_package(Clang CONFIG)

if(${OPEN_STG_ENABLE_DEVELOP_TOOLS} AND ("${OPEN_STG_DEVELOP_TOOLS_TYPE}" STREQUAL "CLANG"))
    if("${LLVM_FOUND}" AND "${CLANG_FOUND}")
        set(OPEN_STG_ENABLE_DEVELOP_TOOLS TRUE)
    else()
        message(WARNING "Llvm or clang is not found.")
        set(OPEN_STG_ENABLE_DEVELOP_TOOLS FALSE)
    endif()
endif()

if(PkgConfig_FOUND)
    pkg_check_modules(LIBBSD IMPORTED_TARGET libbsd)
    pkg_check_modules(LIBSAFEC IMPORTED_TARGET libsafec)
    pkg_check_modules(XDG_DESKTOP_PORTAL IMPORTED_TARGET xdg-desktop-portal)
    pkg_check_modules(GTK4 IMPORTED_TARGET gtk4)
    pkg_check_modules(MCFGHREAD IMPORTED_TARGET mcfgthread)
    pkg_check_modules(LIBDWARF IMPORTED_TARGET libdwarf)
    pkg_check_modules(LIBPOPT IMPORTED_TARGET REQUIRED popt)
endif()

if(${OPEN_STG_OPTION_STRING_PROCESSING_AUTO})
    if(${LIBBSD_FOUND})
        set(OPEN_STG_STRING_PROCESSING_LIBRARY "LIBBSD")
    elseif(${WIN32})
        set(OPEN_STG_STRING_PROCESSING_LIBRARY "STDC")
    else()
        set(OPEN_STG_STRING_PROCESSING_LIBRARY "LIBSAFEC")
    endif()
else()
    if(${OPEN_STG_OPTION_USE_LIBSAFEC})
        set(OPEN_STG_STRING_PROCESSING_LIBRARY "LIBSAFEC")
    elseif(${OPEN_STG_OPTION_USE_STDC11})
        set(OPEN_STG_STRING_PROCESSING_LIBRARY "STDC")
    elseif(${OPEN_STG_OPTION_USE_LIBBSD})
        set(OPEN_STG_STRING_PROCESSING_LIBRARY "LIBBSD")
    else()
        message(FATAL_ERROR "Need to select a string processing library.")
    endif()
endif()
