include(CheckLinkerFlag)

find_program(__lld_found NAMES "lld")
find_program(__wild_found NAMES "ld.wild")
find_program(__mold_found NAMES "ld.mold")
find_program(__gold_found NAMES "ld.gold")
find_program(__bfd_found NAMES "ld.bfd")
if(${OPEN_STG_OPTION_USE_EXTERN_LINKER})
    if(${CMAKE_VERSION} VERSION_GREATER_EQUAL 3.29)
        if(__lld_found)
            message(STATUS "Use lld linker.")
            set(CMAKE_LINKER_TYPE LLD)
        elseif(__mold_found AND ("${CMAKE_SYSTEM_NAME}" MATCHES [=[^(Darwin|iOS|tvOS|watchOS|visionOS|Linux)$]=]))
            message(STATUS "Use mold linker.")
            set(CMAKE_LINKER_TYPE MOLD)
        elseif(__wild_found AND ("${CMAKE_VERSION}" VERSION_GREATER_EQUAL 4.4))
            add_link_options("-fuse-ld=wild")
            set(CMAKE_LINKER_TYPE WILD)
        elseif(__gold_found AND ("${CMAKE_SYSTEM_NAME}" MATCHES [=[^(Linux)$]=]))
            message(STATUS "Use gold linker.")
            set(CMAKE_LINKER_TYPE GOLD)
        elseif(__bfd_found)
            message(STATUS "Use gold linker.")
            set(CMAKE_LINKER_TYPE BFD)
        else()
            set(CMAKE_LINKER_TYPE SYSTEM)
        endif()
    else()
        check_linker_flag(C "-fuse-ld=lld" __support_lld)
        check_linker_flag(C "-fuse-ld=wild" __support_wild)
        check_linker_flag(C "-fuse-ld=mold" __support_mold)
        check_linker_flag(C "-fuse-ld=gold" __support_gold)

        if(__lld_found AND "${__support_lld}")
            message(STATUS "Use lld linker.")
            add_link_options("-fuse-ld=lld")
        elseif(__wild_found AND "${__support_wild}")
            message(STATUS "Use wild linker.")
            add_link_options("-fuse-ld=wild")
        elseif(__mold_found AND "${__support_mold}")
            message(STATUS "Use mold linker.")
            add_link_options("-fuse-ld=mold")
        elseif(__gold_found AND "${__support_gold}")
            message(STATUS "Use gold linker.")
            add_link_options("-fuse-ld=gold")
        elseif(__bfd_found AND "${__support_bfd}")
            message(STATUS "Use gold linker.")
            add_link_options("-fuse-ld=bfd")
        else()

        endif()
    endif()
endif()

if(${__IS_CLANG})
    set(CMAKE_C_CLANG_TIDY clang-tidy)
    set(CMAKE_CXX_CLANG_TIDY clang-tidy)
endif()

cmake_host_system_information(RESULT __parallel QUERY NUMBER_OF_LOGICAL_CORES)
set(CMAKE_BUILD_PARALLEL_LEVEL ${__parallel})
message(STATUS "parallel:${__parallel}")

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<IF:$<CONFIG:Debug>,Debug,Release>")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<IF:$<CONFIG:Debug>,Debug,Release>")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<IF:$<CONFIG:Debug>,Debug,Release>")
set(CMAKE_COMPILE_PDB_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<IF:$<CONFIG:Debug>,Debug,Release>")
