include(CheckLinkerFlag)

if(NOT DEFINED __VCLTL_AND_YYTHUNKS_TAG)
    set(__VCLTL_AND_YYTHUNKS_TAG 1)
    set(VCLTL_VERSION "v5.3.1")
    set(YYTHUNKS_VERSION "v1.2.1")
    set(__WINDOWS_TARGET_PLATFORM_VERSION_REGEX [=[^(Windows10(_19041|_10240)?|Windows8|Windows7|WindowsVista|WindowsXP|WindowsXP64|Windows2000)$]=])
    set(__yythunks_object_binary_dir)
    set(__yythunks_binary_dir)

    function(__download_and_extract_vcltl __vcltl_version)
        if(NOT EXISTS "${__vcltl_binary_dir}")
            message(STATUS "Download VC-LTL")
            set(__vcltl_archive "${CMAKE_BINARY_DIR}/extern/download/vcltl-${__vcltl_version}.7z")
            file(DOWNLOAD "https://github.com/Chuyu-Team/VC-LTL5/releases/download/${__vcltl_version}/VC-LTL-Binary.7z" "${__vcltl_archive}")
            file(ARCHIVE_EXTRACT INPUT "${__vcltl_archive}" DESTINATION "${__vcltl_binary_dir}")
        endif()

        set(VC_LTL_Root "${__vcltl_binary_dir}")
        set(VC_LTL_EnableCMakeInterface TRUE)
        set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
        include("${__vcltl_binary_dir}/config/config.cmake")
    endfunction()

    function(__download_and_extract_yythunk __yythunks_version)
        if(NOT EXISTS "${__yythunks_binary_dir}")
            message(STATUS "Download YYThunks")
            set(__yythunks_archive "${CMAKE_BINARY_DIR}/extern/download/yythunks-${__yythunks_version}.zip")
            file(DOWNLOAD "https://github.com/Chuyu-Team/YY-Thunks/releases/download/${__yythunks_version}/YY-Thunks-Lib.zip" "${__yythunks_archive}")
            file(ARCHIVE_EXTRACT INPUT "${__yythunks_archive}" DESTINATION "${__yythunks_binary_dir}")
        endif()

        if(NOT EISTS "${__yythunks_object_binary_dir}")
            message(STATUS "Download YYThunksObjs.")
            set(__yythunks_object_archive "${CMAKE_BINARY_DIR}/extern/download/yythunksobjs-${__yythunks_version}.zip")
            file(DOWNLOAD "https://github.com/Chuyu-Team/YY-Thunks/releases/download/${__yythunks_version}/YY-Thunks-Objs.zip" "${__yythunks_object_archive}")
            file(ARCHIVE_EXTRACT INPUT "${__yythunks_object_archive}" DESTINATION "${__yythunks_object_binary_dir}")
        endif()
    endfunction()

    macro(__vcltl_and_yythunks_windows_get_version)
        if(NOT ("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows"))
            set(__enable_vcltl_and_yythunks FALSE)
            return()
        else()
            set(__enable_vcltl_and_yythunks TRUE)
        endif()

        if((CMAKE_SYSTEM_PROCESSOR MATCHES [=[^(AMD64|[Xx]64|x86_64)$]=])
            OR (CMAKE_GENERATOR_PLATFORM MATCHES [=[^(x64)$]=])
            OR (CMAKE_VS_PLATFORM_NAME MATCHES [=[^(x64)$]=]))
            set(__enable_vcltl_and_yythunks TRUE)
            set(__yythunks_processor "X86")
            set(__yythunks_system_platform "x86")
        elseif(
            CMAKE_SYSTEM_PROCESSOR MATCHES [=[^(X86|i386|i486|i686)$]=]
            OR (CMAKE_GENERATOR_PLATFORM MATCHES [=[^(Win32)$]=])
            OR (CMAKE_VS_PLATFORM_NAME MATCHES [=[^(Win32)$]=]))
            set(__enable_vcltl_and_yythunks TRUE)
            set(__yythunks_processor "AMD64")
            set(__yythunks_system_platform "x64")
        else()
            set(_enable_vcltl_and_yythunks FALSE)
        endif()

        if("${__yythunks_object_binary_dir}" STREQUAL "")
            set(__yythunks_object_binary_dir "${CMAKE_BINARY_DIR}/extern/YYThunksObjects/${__yythunks_version}")
        endif()

        if("${__yythunks_binary_dir}" STREQUAL "")
            set(__yythunks_binary_dir "${CMAKE_BINARY_DIR}/extern/YYThunksLibraries/${__yythunks_version}")
        endif()

        if("${__vcltl_binary_dir}" STREQUAL "")
            set(__vcltl_binary_dir "${CMAKE_BINARY_DIR}/extern/VC-LTL5/${__vcltl_version}")
        endif()

        if(__enable_vcltl_and_yythunks)
            if("${WINDOWS_TARGET_PLATFORM_VERSION}" MATCHES [=[^(Windows10(_19041)?)$]=])
                set(__yythunks_system_version "10.0.19041.0")
                set(WindowsTargetPlatformMinVersion "${__yythunks_system_version}")
                set(__yythunks_object_file_name "YY_Thunks_for_Win10.0.19041.obj")
            elseif("${WINDOWS_TARGET_PLATFORM_VERSION}" MATCHES [=[^(Windows10_10240)$]=])
                set(__yythunks_system_version "10.0.10240.0")
                set(WindowsTargetPlatformMinVersion "${__yythunks_system_version}")
                set(__yythunks_object_file_name "YY_Thunks_for_Win10.0.10240.obj")
            elseif("${WINDOWS_TARGET_PLATFORM_VERSION}" MATCHES [=[^(Windows8)$]=])
                set(__yythunks_system_version "6.2.9200.0")
                set(WindowsTargetPlatformMinVersion "${__yythunks_system_version}")
                set(__yythunks_object_file_name "YY_Thunks_for_Win8.obj")
            elseif("${WINDOWS_TARGET_PLATFORM_VERSION}" MATCHES [=[^(Windows7)$]=])
                set(__yythunks_system_version "6.1.7600.0")
                set(WindowsTargetPlatformMinVersion "${__yythunks_system_version}")
                set(__yythunks_object_file_name "YY_Thunks_for_Win7.obj")
            elseif("${WINDOWS_TARGET_PLATFORM_VERSION}" MATCHES [=[^(WindowsVista)$]=])
                set(__yythunks_system_version "6.0.6000.0")
                set(WindowsTargetPlatformMinVersion "${__yythunks_system_version}")
                set(__yythunks_object_file_name "YY_Thunks_for_Vista.obj")
            elseif("${WINDOWS_TARGET_PLATFORM_VERSION}" MATCHES [=[^(WindowsXP64)$]=])
                set(__yythunks_system_version "5.2.3790.1830")
                set(WindowsTargetPlatformMinVersion "${__yythunks_system_version}")
                set(__yythunks_object_file_name "YY_Thunks_for_WinXP.obj")
            elseif("${WINDOWS_TARGET_PLATFORM_VERSION}" MATCHES [=[^(WindowsXP)$]=])
                set(__yythunks_system_version "5.1.2600.0")
                set(WindowsTargetPlatformMinVersion "${__yythunks_system_version}")
                set(__yythunks_object_file_name "YY_Thunks_for_WinXP.obj")
            elseif("${WINDOWS_TARGET_PLATFORM_VERSION}" MATCHES [=[^(Windows2000)$]=])
                set(__yythunks_system_version "5.0.2195.0")
                set(__yythunks_object_file_name "YY_Thunks_for_Win2K.obj")
            else()
                set(__enable_vcltl_and_yythunks FALSE)
            endif()
        endif()
    endmacro()

    function(__real_link_to_vcltl_and_yythunk_link __target __visibility)
        target_link_libraries("${__target}" "${__visibility}" VC_LTL)
        target_sources("${__target}" "${__visibility}" "${__yythunks_object_binary_dir}/objs/${__yythunks_system_platform}/${__yythunks_object_file_name}")

        if("${WINDOWS_TARGET_PLATFORM_VERSION}" MATCHES [=[^(WindowsXP64|WindowsXP|Windows2000)$]=])
            get_target_property("${__target}" TYPE __target_type)

            if("${__target_type}" MATCHES [=[^(SHARED_LIBRARY|MODULE_LIBRARY)$]=])
                target_link_options("${__target}" "${__visibility}" [=[/SUBSYSTEM:CONSOLE",5.1"]=] [=[/ENTRY:DllMainCRTStartupForYY_Thunks]=])

                if(__yythunks_processor MATCHES [=[^(X86)$]=])
                    target_link_options("${__target}" "${__visibility}" [=[/ALTERNATENAME:_YY_ThunksOriginalDllMainCRTStartup@12=__DllMainCRTStartup@12]=])
                else()
                    target_link_options("${__target}" "${__visibility}" [=[/ALTERNATENAME:YY_ThunksOriginalDllMainCRTStartup=_DllMainCRTStartup]=])
                endif()
            endif()
        endif()
    endfunction()

    function(__real_link_to_vcltl_and_yythunk_lld_link __target __visibility)
        if(NOT __enable_vcltl_and_yythunks)
            return()
        endif()

        target_link_libraries("${__target}" "${__visibility}" VC_LTL)

        # YYThunks
        file(TO_NATIVE_PATH "${__YYTHUNKS_BINARY_DIR}" __yythunks_binary_native_dir)
        set(__yythunks_library_directory "${__yythunks_binary_native_dir}/Lib/${__yythunks_system_version}/${__yythunks_system_platform}")

        if(NOT EXISTS "${__yythunks_library_directory}")
            message(FATAL_ERROR "Version ${__yythunks_system_version} dose not exists.(YYThunks)")
        endif()

        # target_link_options("${__target}" BEFORE "${__visibility}" "/LIBPATH:${__yythunks_library_directory}")
        target_link_directories("${__target}" BEFORE "${__visibility}" "${__yythunks_library_directory}")
        get_target_property("${__target}" TYPE __target_type)

        if("${__target_type}" MATCHES [=[^(SHARED_LIBRARY|MODULE_LIBRARY)$]=])
            target_link_options("${__target}" "${__visibility}" [=[/SUBSYSTEM:CONSOLE",5.1"]=] [=[/ENTRY:DllMainCRTStartupForYY_Thunks]=])

            if("${__yythunks_processor}" MATCHES [=[^(X86)$]=])
                target_link_options("${__target}" "${__visibility}" [=[/ALTERNATENAME:_YY_ThunksOriginalDllMainCRTStartup@12=__DllMainCRTStartup@12]=])
            else()
                target_link_options("${__target}" "${__visibility}" [=[/ALTERNATENAME:YY_ThunksOriginalDllMainCRTStartup=_DllMainCRTStartup]=])
            endif()
        endif()
    endfunction()

    function(link_to_vcltl_and_yythunk __target __visibility)
        if(NOT __enable_vcltl_and_yythunks)
            return()
        endif()

        if("${CMAKE_C_COMPILER_ID}" STREQUAL "MSVC")
            __real_link_to_vcltl_and_yythunk_link("${__target}" "${__visibility}")
        elseif("${CMAKE_VERSION}" VERSION_GREATER_EQUAL 3.29)
            if(("${CMAKE_C_COMPILER}" STREQUAL "Clang") AND ("${CMAKE_C_COMPILER_LINKER_FRONTEND_VARIANT}" STREQUAL "MSVC"))
                __real_link_to_vcltl_and_yythunk_lld_link("${__target}" "${__visibility}")
            endif()
        else()
            check_linker_flag(C "/DEBUG" __support_msvc_style)

            if("${__support_msvc_style}")
                __real_link_to_vcltl_and_yythunk_lld_link("${__target}" "${__visibility}")
            endif()
        endif()
    endfunction()

    macro(enable_vcltl_and_yythunks)
        if(NOT "${CMAKE_SYSTEM_NAME}" STREQUAL "Windows")
        else()
            cmake_parse_arguments(__args "GLOBAL;IMPORT_TARGET" "" "" ${ARGN})
            set(__is_global "${__args_GLOBAL}")
            set(__import_target "${__args_IMPORT_TARGET}")
            __vcltl_and_yythunks_windows_get_version()

            if("${__enable_vcltl_and_yythunks}")
                __download_and_extract_vcltl("${VCLTL_VERSION}")
                __download_and_extract_yythunk("${YYTHUNKS_VERSION}")
            endif()
        endif()
    endmacro()
endif()
