set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(CMAKE_LINKER_TYPE LLD)
list(APPEND CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld")
list(APPEND CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld")
list(APPEND CMAKE_STATIC_LINKER_FLAGS "-fuse-ld=lld")
list(APPEND CMAKE_MODULE_LINKER_FLAGS "-fuse-ld=lld")
