set(CMAKE_C_COMPILER cl.exe)
set(CMAKE_CXX_COMPILER cl.exe)
set(CMAKE_LINKER_TYPE MSVC)

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_GENERATOR_PLATFORM x64)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_VS_PLATFORM_NAME AMD64)
