find_package(spdlog CONFIG REQUIRED)
find_package(Catch2 CONFIG REQUIRED)
find_package(SDL2 CONFIG REQUIRED)
find_package(SDL2_image CONFIG REQUIRED)
find_package(SDL2_ttf CONFIG REQUIRED)
find_package(SDL2PP REQUIRED)
find_package(Boost REQUIRED COMPONENTS program_options)
find_package(boost_program_options REQUIRED CONFIG)
find_package(libconfig CONFIG REQUIRED)