find_package(spdlog CONFIG REQUIRED)
find_package(Catch2 CONFIG REQUIRED)
find_package(SDL2 CONFIG REQUIRED)
find_package(SDL2_image CONFIG REQUIRED)
find_package(SDL2_ttf CONFIG REQUIRED)
find_package(SDL2_mixer CONFIG REQUIRED)
find_package(libconfig CONFIG REQUIRED)
find_package(Boost REQUIRED COMPONENTS thread program_options)

find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
    
    pkg_check_modules(LIBSAFEC QUIET IMPORTED_TARGET libsafec) 
    message(STATUS "LIBSAFEC_FOUND: ${LIBSAFEC_FOUND}")
endif()
