
if(DEFINED RSUT_SOURCE_DIR)
    set(__RUST_SOURCE_DIR "${RUST_SOURCE_DIR}" CACHE PATH)
else()
    set(__RUST_SOURCE_DIR "${CMAKE_SOURCE_DIR}" CACHE PATH)
endif()

find_file(__RUST_CARGO_FILE_FOUND NAMES __RSUT_CARGO_FILE PATHS "${__RUST_SOURCE_DIR}/Cargo.toml")
find_program(CARGO_EXECUTABLE_FILE_PATH NAMES "cargo" REQUIRED)
find_program(RUSTC_EXECUTABLE_FILE_PATH NAMES "rustc" REQUIRED)

